# Generated by Django 3.2.22 on 2023-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.png', upload_to='products'),
        ),
    ]
